In [2]:
import numpy as np

## Data types & attributes 

In [36]:
a1=np.array([1,3,4])
a1

array([1, 3, 4])

In [37]:
 type(a1)

numpy.ndarray

In [38]:
a2=np.array([[1,5.3,4],[7,3,2.6]])

In [39]:
a2

array([[1. , 5.3, 4. ],
       [7. , 3. , 2.6]])

In [40]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [10, 11, 12]],

       [[ 7,  8,  9],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
type(a3)


numpy.ndarray

In [42]:
a2.shape

(2, 3)

In [43]:
import pandas as pd 

In [44]:

df = pd.DataFrame(a3.reshape(-1, 3))  # 6 rows, 3 columns
print(df)


    0   1   2
0   1   2   3
1   4   5   6
2  10  11  12
3   7   8   9
4  13  14  15
5  16  17  18


In [45]:
import numpy as np

a3 = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [10, 11, 12]],
    
    [[7, 8, 9],
     [13, 14, 15],
     [16, 17, 18]]
])


In [47]:
de=pd.DataFrame(a2)

In [48]:
de

0    1    2
0  1.0  5.3  4.0
1  7.0  3.0  2.6

In [8]:
one=np.ones((2,2))

In [9]:
one

array([[1., 1.],
       [1., 1.]])

In [13]:
arrays= np.arange(2,14,1)
arrays

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [21]:
np.random.seed(2)
arr_2 = np.random.random((5,3))
arr_2

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467],
       [0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987]])