###introduction to numpy 

In [1]:
import numpy as np


In [2]:
a1=np.array([2,4,4])
a1

array([2, 4, 4])

In [4]:
a2=np.array([[3,4,3],[2,2,8]])
a2

array([[3, 4, 3],
       [2, 2, 8]])

### arrays creations

### of matrices in numpy

In [12]:


a4 = np.zeros((7, 6))
print("Zero matrix is:\n")
a4


Zero matrix is:



array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:


a5= np.full((7, 6),7)
print(" matrix is:\n")
a5


 matrix is:



array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])