##Dot product example


In [3]:
import numpy as np
import pandas as pd

In [5]:
np.random.seed(0)

sales_amounts=np.random.randint(30, size= (5,3))
sales_amounts

array([[12, 15, 21],
       [ 0,  3, 27],
       [ 3,  7,  9],
       [19, 21, 18],
       [ 4, 23,  6]], dtype=int32)

In [8]:
weekly_sales=pd.DataFrame(sales_amounts,
                          index=["Mon","Tue","wed","Thur","Fri"],
                          columns=["Almond "," Penut","Cashew"])
weekly_sales

Almond    Penut  Cashew
Mon        12      15      21
Tue         0       3      27
wed         3       7       9
Thur       19      21      18
Fri         4      23       6

In [10]:
prices=np.array([10,8,15])
prices

array([10,  8, 15])

In [13]:
butter_prices=pd.DataFrame(prices.reshape(1,3),
                          index=["prices"],
                           columns=["Almond "," Penut","Cashew"])
                          
butter_prices

Almond    Penut  Cashew
prices       10       8      15

In [7]:
Random_array=np.random.randint(10,size=(3,5))
Random_array

array([[9, 2, 3, 7, 8],
       [3, 8, 9, 9, 3],
       [5, 9, 9, 4, 4]], dtype=int32)

In [8]:
np.sort(Random_array)

array([[2, 3, 7, 8, 9],
       [3, 3, 8, 9, 9],
       [4, 4, 5, 9, 9]], dtype=int32)

In [9]:
np.argsort(Random_array)

array([[1, 2, 3, 4, 0],
       [0, 4, 1, 2, 3],
       [3, 4, 0, 1, 2]])

In [10]:
Random_array


array([[9, 2, 3, 7, 8],
       [3, 8, 9, 9, 3],
       [5, 9, 9, 4, 4]], dtype=int32)

In [1]:
import numpy as np

In [6]:
a1 =np.array([1,2,3,4,5,6,7,8,9,])
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a1 =np.array([1,2,3,4,5,6,7,8,9,])
print("slicing of the index is ")
a1[2:8]



slicing of the index is 


array([3, 4, 5, 6, 7, 8])

In [21]:
print("with step :",a1[1:9:3])

with step : [2 5 8]


In [24]:
print(" negitive indexing is : " ,a1[-2])

 negitive indexing is :  8


## 

In [25]:
a2=np.array([[1,2,3],
            [4,5,6],
             [7,8,9]
            ])

In [26]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a2.shape

(3, 3)

In [37]:
a2[2,2]

np.int64(9)

In [39]:
unsorted_arr=np.array([4,6,2,4,7,2,6,9,0,1,3,5,7,8,11])
np.sort(unsorted_arr)

array([ 0,  1,  2,  2,  3,  4,  4,  5,  6,  6,  7,  7,  8,  9, 11])